services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: skinet
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data 
volumes:
  postgres-data: 